# If you want to set up another Travis CI service for your fork (not branch),
# you can alter it to disable tests and notification for the official repo.
if: repo = Attnam/ivan

sudo: required
dist: trusty

language: cpp

matrix:

  include:

    - env: CXXFLAGS= IVAN_PLATFORM=
      os: linux
      compiler: clang

    - env: CXXFLAGS=-DWIZARD IVAN_PLATFORM=
      os: linux
      compiler: clang

    - env: CXXFLAGS= IVAN_PLATFORM=
      os: osx
      compiler: clang

    - env: CXXFLAGS=-DWIZARD IVAN_PLATFORM=
      os: osx
      compiler: clang

    - env: CXXFLAGS= IVAN_PLATFORM=
      os: linux
      compiler: gcc

    - env: CXXFLAGS=-DWIZARD IVAN_PLATFORM=
      os: linux
      compiler: gcc

    - env: CXXFLAGS= IVAN_PLATFORM=
      os: osx
      compiler: gcc

    - env: CXXFLAGS=-DWIZARD IVAN_PLATFORM=
      os: osx
      compiler: gcc

    - env: CXXFLAGS=-DWIZARD IVAN_PLATFORM=
      os: linux
      compiler: gcc

    - env: CXXFLAGS=-DWIZARD IVAN_PLATFORM=osx SDL2DIR=$HOME/Thirdparty/Frameworks
      os: osx
      compiler: clang

cache:
  directories:
    - $HOME/Thirdparty/Frameworks

addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-mixer-dev

before_install:
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - export IVAN_BUILD_DIR=${TRAVIS_BUILD_DIR}/build
  - export IVAN_FILE_VERSION=${TRAVIS_TAG#v}
  - if [[ "$TRAVIS_OS_NAME" = osx ]]; then ./ci/osx/requirements.sh; fi
  - if [[ "$IVAN_PLATFORM" = win ]]; then ./ci/win/requirements.sh; fi

script:
  - mkdir build
  - cd build
  - if [[ -z "$IVAN_PLATFORM" ]]; then cmake .. -G "Unix Makefiles" -DCMAKE_CXX_FLAGS="-Werror -Wno-format-security -Wno-undefined-var-template -Wno-unknown-warning-option ${CXXFLAGS}"; fi
  - if [[ -n "$IVAN_PLATFORM" ]]; then "../ci/$IVAN_PLATFORM/build.sh"; fi
  - make
  - make igor
  - make mihail
  - if [[ -z "$IVAN_PLATFORM" ]]; then sudo make install; fi
  - if [[ -n "$IVAN_PLATFORM" ]]; then make install; fi
  - if [[ -n "$IVAN_PLATFORM" ]]; then "../ci/$IVAN_PLATFORM/package.sh"; fi

# https://docs.travis-ci.com/user/deployment/releases
deploy:
  provider: releases
  api_key: $GH_API_KEY
  skip_cleanup: true
  file_glob: true
  file:
    - $IVAN_BUILD_DIR/$IVAN_PLATFORM/*.zip
    - $IVAN_BUILD_DIR/$IVAN_PLATFORM/*.dmg
  on:
    condition: '"$IVAN_PLATFORM" =~ ^(win|osx)$'
    repo: Attnam/ivan
    tags: true
    branch: master
