sudo: required
dist: trusty

language: cpp

matrix:

  include:

    - env: CXXFLAGS= IVAN_PLATFORM=
      os: linux
      compiler: clang

    - env: CXXFLAGS=-DWIZARD IVAN_PLATFORM=
      os: linux
      compiler: clang

    - env: CXXFLAGS= IVAN_PLATFORM=
      os: osx
      compiler: clang

    - env: CXXFLAGS=-DWIZARD IVAN_PLATFORM=
      os: osx
      compiler: clang

    - env: CXXFLAGS= IVAN_PLATFORM=
      os: linux
      compiler: gcc

    - env: CXXFLAGS=-DWIZARD IVAN_PLATFORM=
      os: linux
      compiler: gcc

    - env: CXXFLAGS= IVAN_PLATFORM=
      os: osx
      compiler: gcc

    - env: CXXFLAGS=-DWIZARD IVAN_PLATFORM=
      os: osx
      compiler: gcc

    - env: CXXFLAGS=-DWIZARD IVAN_PLATFORM='IvanWin'
      os: linux
      compiler: gcc

addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-mixer-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install sdl2 sdl2_mixer; fi
  - if [[ "$IVAN_PLATFORM" == "IvanWin" ]]; then source ./mxe/${IVAN_PLATFORM}/requirements.sh; fi
  - if [[ "$IVAN_PLATFORM" == "IvanWin" ]]; then source ./mxe/${IVAN_PLATFORM}/version.sh; fi

script:
  - mkdir build
  - cd build
  - if [[ "$IVAN_PLATFORM" == "IvanWin" ]]; then ../mxe/${IVAN_PLATFORM}/build.sh; else cmake .. -G "Unix Makefiles" -DCMAKE_CXX_FLAGS="-Werror -Wno-format-security -Wno-undefined-var-template -Wno-unknown-warning-option $CXXFLAGS"; fi
  - make
  - make igor
  - make mihail
  - sudo make install

before_deploy:
  - if [[ "$IVAN_PLATFORM" == "IvanWin" ]]; then ${TRAVIS_BUILD_DIR}/mxe/${IVAN_PLATFORM}/package.sh; fi

deploy:
  provider: releases
  api_key: "$GH_API_KEY"
  file:
    - "$(ls ${TRAVIS_BUILD_DIR}/build/${IVAN_PLATFORM}/ivan/${IVAN_PLATFORM}${IVAN_FILE_VERSION}.zip)"
  skip_cleanup: true
  on:
    condition: "$IVAN_PLATFORM = IvanWin"
    branches: 
      only:
        - master
    tags: true
