/*
 *
 *  Iter Vehemens ad Necem (IVAN)
 *  Copyright (C) Timo Kiviluoto
 *  Released under the GNU General
 *  Public License
 *
 *  See LICENSING which should be included
 *  along with this file for more details
 *
 */

#ifndef __CONFDEF_H__
#define __CONFDEF_H__

/*
 * Configuration defines of IVAN
 */

#define SOLID_ID (1 << 12)

#define VALPURIUM (SOLID_ID + 1)
#define TIN (SOLID_ID + 2)
#define COPPER (SOLID_ID + 3)
#define BRONZE (SOLID_ID + 4)
#define VERDIGRIS (SOLID_ID + 5)
#define DEEP_BRONZE (SOLID_ID + 6)
#define BRASS (SOLID_ID + 7)
#define HEPATIZON (SOLID_ID + 8)
#define OCTIRON (SOLID_ID + 9)
#define ORICHALCUM (SOLID_ID + 10)
#define SILVER (SOLID_ID + 11)
#define MOON_SILVER (SOLID_ID + 12)
#define FAIRY_STEEL (SOLID_ID + 13)
#define MITHRIL (SOLID_ID + 14)
#define GALVORN (SOLID_ID + 15)
#define STAR_METAL (SOLID_ID + 16)
#define PLATINUM (SOLID_ID + 17)
#define LEAD (SOLID_ID + 18)
#define GOLD (SOLID_ID + 19)
#define DARK_GOLD (SOLID_ID + 20)
#define DARK_MATTER (SOLID_ID + 21)
#define PETRIFIED_DARK (SOLID_ID + 22)
#define ELECTRUM (SOLID_ID + 23)
#define ALUMINIUM (SOLID_ID + 24)
#define NICKEL (SOLID_ID + 25)
#define COBALT (SOLID_ID + 26)
#define TUNGSTEN (SOLID_ID + 27)
#define IRIDIUM (SOLID_ID + 28)
#define PALLADIUM (SOLID_ID + 29)
#define CHROME (SOLID_ID + 30)
#define TITANITE (SOLID_ID + 31)
#define LINEN_CLOTH (SOLID_ID + 32)
#define HEMP_CLOTH (SOLID_ID + 33)
#define WOOL_CLOTH (SOLID_ID + 34)
#define FELT (SOLID_ID + 35)
#define FABRIC (SOLID_ID + 36)
#define ELF_CLOTH (SOLID_ID + 37)
#define NYMPH_HAIR (SOLID_ID + 38)
#define OMMEL_HAIR (SOLID_ID + 39)
#define TROLL_WOOL (SOLID_ID + 40)
#define ANGEL_HAIR (SOLID_ID + 41)
#define SPIDER_SILK (SOLID_ID + 42)
#define GOSSAMER (SOLID_ID + 43)
#define SPIRIT_CLOTH (SOLID_ID + 44)
#define HUMAN_SKIN (SOLID_ID + 45)
#define WOLF_SKIN (SOLID_ID + 46)
#define BEAR_SKIN (SOLID_ID + 47)
#define SNAKE_SKIN (SOLID_ID + 48)
#define CROCODILE_SKIN (SOLID_ID + 49)
#define BASILISK_SKIN (SOLID_ID + 50)
#define NAGA_SKIN (SOLID_ID + 51)
#define WYVERN_HIDE (SOLID_ID + 52)
#define HYDRA_HIDE (SOLID_ID + 53)
#define LEATHER (SOLID_ID + 54)
#define BLACK_LEATHER (SOLID_ID + 55)
#define HARDENED_LEATHER (SOLID_ID + 56)
#define BOILED_LEATHER (SOLID_ID + 57)
#define QUILTED_LEATHER (SOLID_ID + 58)
#define STUDDED_LEATHER (SOLID_ID + 59)
#define TROLL_HIDE (SOLID_ID + 60)
#define IMP_HIDE (SOLID_ID + 61)
#define DRAGON_HIDE (SOLID_ID + 62)
#define OUROBOROS_HIDE (SOLID_ID + 63)
#define OSTRICH_FEATHER (SOLID_ID + 64)
#define HARPY_FEATHER (SOLID_ID + 65)
#define GRIFFON_FEATHER (SOLID_ID + 66)
#define PHOENIX_FEATHER (SOLID_ID + 67)
#define STYMPHALIAN_FEATHER (SOLID_ID + 68)
#define GOLDEN_EAGLE_FEATHER (SOLID_ID + 69)
#define SEA_WEED (SOLID_ID + 70)
#define FISH_SCALE (SOLID_ID + 71)
#define MERMAID_HAIR (SOLID_ID + 72)
#define SELKIE_SKIN (SOLID_ID + 73)
#define SEA_SERPENT_SCALE (SOLID_ID + 74)
#define KRAKEN_HIDE (SOLID_ID + 75)
#define LEVIATHAN_HIDE (SOLID_ID + 76)
#define DREAM_CLOTH (SOLID_ID + 77)
#define RAINBOW_CLOTH (SOLID_ID + 78)
#define SHADOW_CLOTH (SOLID_ID + 79)
#define NYLON (SOLID_ID + 80)
#define ELASTI_CLOTH (SOLID_ID + 81)
#define ETEX_CLOTH (SOLID_ID + 82)
#define SMART_CLOTH (SOLID_ID + 83)
#define FLEXI_CLOTH (SOLID_ID + 84)
#define KEVLAR (SOLID_ID + 85)
#define SYNTH_CLOTH (SOLID_ID + 86)
#define NANO_FIBER (SOLID_ID + 87)
#define LATEX (SOLID_ID + 88)
#define RUBBER (SOLID_ID + 89)
#define PLASTIC (SOLID_ID + 90)
#define HARDENED_PLASTIC (SOLID_ID + 91)
#define STAINLESS_STEEL (SOLID_ID + 92)
#define PLASTIC_STEEL (SOLID_ID + 93)
#define DURALLOY (SOLID_ID + 94)
#define VITRELLOY (SOLID_ID + 95)
#define CHAR_COAL (SOLID_ID + 96)
#define COAL (SOLID_ID + 97)
#define JET (SOLID_ID + 98)
#define CARBIDE (SOLID_ID + 99)
#define FOLDED_CARBIDE (SOLID_ID + 100)
#define FULLERITE (SOLID_ID + 101)
#define URANIUM (SOLID_ID + 102)
#define SOLARIUM (SOLID_ID + 103)
#define NEUTRONIUM (SOLID_ID + 104)
#define MAGIC_CRYSTAL (SOLID_ID + 105)
#define ARCANITE (SOLID_ID + 106)
#define OCCULTUM (SOLID_ID + 107)
#define SAND_STONE (SOLID_ID + 108)
#define RED_SAND_STONE (SOLID_ID + 109)
#define GLASS (SOLID_ID + 110)
#define PEARL_GLASS (SOLID_ID + 111)
#define ILLITHIUM (SOLID_ID + 112)
#define ICE (SOLID_ID + 113)
#define RED_ICE (SOLID_ID + 114)
#define JOTUN_ICE (SOLID_ID + 115)
#define PRIMORDIAL_ICE (SOLID_ID + 116)
#define GRASS (SOLID_ID + 117)
#define DARK_GRASS (SOLID_ID + 118)
#define MYCELIUM (SOLID_ID + 119)
#define LEAF (SOLID_ID + 120)
#define PALM_LEAF (SOLID_ID + 121)
#define WITCH_BARK (SOLID_ID + 122)
#define DARK_PETAL (SOLID_ID + 123)
#define STEEL_LEAF (SOLID_ID + 124)
#define CHLOROPHYTE (SOLID_ID + 125)
#define PAPYRUS (SOLID_ID + 126)
#define PARCHMENT (SOLID_ID + 127)
#define VELLUM (SOLID_ID + 128)
#define PAPER_BOARD (SOLID_ID + 129)
#define FUNGI_WOOD (SOLID_ID + 130)
#define SPRUCE_WOOD (SOLID_ID + 131)
#define SYCAMORE_WOOD (SOLID_ID + 132)
#define ELM_WOOD (SOLID_ID + 133)
#define ASH_WOOD (SOLID_ID + 134)
#define CYPRESS_WOOD (SOLID_ID + 135)
#define HOLLY_WOOD (SOLID_ID + 136)
#define YEW_WOOD (SOLID_ID + 137)
#define BEECH_WOOD (SOLID_ID + 138)
#define BAMBOO_WOOD (SOLID_ID + 139)
#define MAHOGANY_WOOD (SOLID_ID + 140)
#define BALSA_WOOD (SOLID_ID + 141)
#define PINE_WOOD (SOLID_ID + 142)
#define FIR_WOOD (SOLID_ID + 143)
#define BIRCH_WOOD (SOLID_ID + 144)
#define OAK_WOOD (SOLID_ID + 145)
#define TEAK_WOOD (SOLID_ID + 146)
#define EBONY_WOOD (SOLID_ID + 147)
#define KAURI_WOOD (SOLID_ID + 148)
#define RATA_WOOD (SOLID_ID + 149)
#define SIDGURE_WOOD (SOLID_ID + 150)
#define PETRIFIED_WOOD (SOLID_ID + 151)
#define HUMAN_NAIL (SOLID_ID + 152)
#define CHITINE (SOLID_ID + 153)
#define BUFFALO_HORN (SOLID_ID + 154)
#define MOOSE_ANTLER (SOLID_ID + 155)
#define UNICORN_HORN (SOLID_ID + 156)
#define TURTLE_SHELL (SOLID_ID + 157)
#define SEA_SHELL (SOLID_ID + 158)
#define DRAGON_BONE (SOLID_ID + 159)
#define WAX (SOLID_ID + 160)
#define GRAVEL (SOLID_ID + 161)
#define MORAINE (SOLID_ID + 162)
#define COBBLE_STONE (SOLID_ID + 163)
#define LIME_STONE (SOLID_ID + 164)
#define SHALE (SOLID_ID + 165)
#define OBSIDIAN (SOLID_ID + 166)
#define MARBLE (SOLID_ID + 167)
#define BASALT (SOLID_ID + 168)
#define JASPER (SOLID_ID + 169)
#define JACINTH (SOLID_ID + 170)
#define AGATE (SOLID_ID + 172)
#define TOURMALINE (SOLID_ID + 173)
#define CHALCEDONY (SOLID_ID + 174)
#define CALCITE (SOLID_ID + 175)
#define GNEISS (SOLID_ID + 176)
#define SLATE (SOLID_ID + 177)
#define GRANITE (SOLID_ID + 178)
#define BLACK_GRANITE (SOLID_ID + 179)
#define CHALK (SOLID_ID + 180)
#define FLINT (SOLID_ID + 181)
#define CITRINE (SOLID_ID + 182)
#define LAPIS_LAZULI (SOLID_ID + 183)
#define AMBER (SOLID_ID + 184)
#define OPAL (SOLID_ID + 185)
#define ONYX (SOLID_ID + 186)
#define SLADE (SOLID_ID + 187)
#define NACRE (SOLID_ID + 188)
#define PEARL (SOLID_ID + 189)
#define CORAL (SOLID_ID + 190)
#define DEEP_CORAL (SOLID_ID + 191)
#define HALCYON (SOLID_ID + 192)
#define MILKY_QUARTZ (SOLID_ID + 193)
#define QUARTZITE (SOLID_ID + 194)
#define ROSE_QUARTZ (SOLID_ID + 195)
#define NETHER_QUARTZ (SOLID_ID + 196)
#define AMETHYST (SOLID_ID + 197)
#define TOPAZ (SOLID_ID + 198)
#define SAPPHIRE (SOLID_ID + 199)
#define EMERALD (SOLID_ID + 200)
#define RUBY (SOLID_ID + 201)
#define DIAMOND (SOLID_ID + 202)
#define BLACK_DIAMOND (SOLID_ID + 203)
#define JADEITE (SOLID_ID + 204)
#define MALACHITE (SOLID_ID + 205)
#define NEPHRITE (SOLID_ID + 206)
#define BLACK_JADE (SOLID_ID + 207)
#define RED_JADE (SOLID_ID + 208)
#define GREEN_JADE (SOLID_ID + 209)
#define BLUE_JADE (SOLID_ID + 210)
#define WHITE_JADE (SOLID_ID + 211)
#define ROCK_CRYSTAL (SOLID_ID + 212)
#define PURPLE_CRYSTAL (SOLID_ID + 213)
#define BLUE_CRYSTAL (SOLID_ID + 214)
#define GREEN_CRYSTAL (SOLID_ID + 215)
#define SUN_CRYSTAL (SOLID_ID + 216)
#define CONCRETE (SOLID_ID + 217)
#define HARDENED_CONCRETE (SOLID_ID + 218)
#define SUPER_CONCRETE (SOLID_ID + 219)
#define SULFUR (SOLID_ID + 220)
#define BRIM_STONE (SOLID_ID + 221)
#define CLAY (SOLID_ID + 222)
#define HARDENED_CLAY (SOLID_ID + 223)
#define PORCELAIN (SOLID_ID + 224)
#define ROCK_SALT (SOLID_ID + 225)
#define AEGI_SALT (SOLID_ID + 226)
#define ALABASTER (SOLID_ID + 227)
#define HEMATITE (SOLID_ID + 228)
#define PYRITE (SOLID_ID + 229)
#define HARDENED_ASH (SOLID_ID + 230)
#define PSYPHER (SOLID_ID + 231)

#define ORGANIC_ID (2 << 12)

#define PLANT_FIBER (ORGANIC_ID + 1)
#define MUTANT_PLANT_FIBER (ORGANIC_ID + 2)
#define BANANA_PEEL (ORGANIC_ID + 3)
#define BANANA_FLESH (ORGANIC_ID + 4)
#define HOLY_BANANA_FLESH (ORGANIC_ID + 5)
#define KIWI_FLESH (ORGANIC_ID + 6)
#define PINEAPPLE_FLESH (ORGANIC_ID + 7)
#define CARROT_FLESH (ORGANIC_ID + 8)
#define MANGO_FLESH (ORGANIC_ID + 9)
#define KELP (ORGANIC_ID + 10)
#define PLANKTON (ORGANIC_ID + 11)
#define DARK_BREAD (ORGANIC_ID + 12)
#define FLAT_BREAD (ORGANIC_ID + 13)
#define RYE_BREAD (ORGANIC_ID + 14)
#define BANANA_STOLLEN (ORGANIC_ID + 15)
#define CHEESE (ORGANIC_ID + 16)
#define CHOCOLATE (ORGANIC_ID + 17)
#define SCHOOL_FOOD (ORGANIC_ID + 18)
#define OMMEL_CERUMEN (ORGANIC_ID + 19)
#define BONE (ORGANIC_ID + 20)
#define WHALE_BONE (ORGANIC_ID + 21)
#define WRAITH_BONE (ORGANIC_ID + 22)
#define OMMEL_BONE (ORGANIC_ID + 23)
#define SHARK_TOOTH (ORGANIC_ID + 24)
#define TROLL_TUSK (ORGANIC_ID + 25)
#define MAMMOTH_TUSK (ORGANIC_ID + 26)
#define OMMEL_TOOTH (ORGANIC_ID + 27)
#define RESIDUUM (ORGANIC_ID + 28)

#define GAS_ID (3 << 12)

#define AIR (GAS_ID + 1)
#define VACUUM (GAS_ID + 2)
#define ETHER (GAS_ID + 3)
#define SMOKE (GAS_ID + 4)
#define SKUNK_SMELL (GAS_ID + 5)
#define ECTOPLASM (GAS_ID + 6)
#define MAGIC_VAPOUR (GAS_ID + 7)
#define EVIL_WONDER_STAFF_VAPOUR (GAS_ID + 8)
#define GOOD_WONDER_STAFF_VAPOUR (GAS_ID + 9)
#define FART (GAS_ID + 10)
#define MUSTARD_GAS (GAS_ID + 11)
#define SLEEPING_GAS (GAS_ID + 12)

#define LIQUID_ID (4 << 12)

#define ANTIDOTE_LIQUID (LIQUID_ID + 1)
#define CURE_ALL_LIQUID (LIQUID_ID + 2)
#define HEALING_LIQUID (LIQUID_ID + 3)
#define MAGIC_LIQUID (LIQUID_ID + 4)
#define PEA_SOUP (LIQUID_ID + 5)
#define CHICKEN_SOUP (LIQUID_ID + 6)
#define PORRIDGE (LIQUID_ID + 7)
#define CUSTARD (LIQUID_ID + 8)
#define MILK (LIQUID_ID + 9)
#define HONEY (LIQUID_ID + 10)
#define COCA_COLA (LIQUID_ID + 11)
#define INK (LIQUID_ID + 12)
#define BRINE (LIQUID_ID + 13)
#define WATER (LIQUID_ID + 14)
#define VALDEMAR (LIQUID_ID + 15)
#define VODKA (LIQUID_ID + 16)
#define CIDER (LIQUID_ID + 17)
#define WHITE_WINE (LIQUID_ID + 18)
#define RED_WINE (LIQUID_ID + 19)
#define BEER (LIQUID_ID + 20)
#define ELF_ALE (LIQUID_ID + 21)
#define DWARF_BEER (LIQUID_ID + 22)
#define BROWN_SLIME (LIQUID_ID + 23)
#define GREEN_SLIME (LIQUID_ID + 24)
#define POISON_LIQUID (LIQUID_ID + 25)
#define PEPSI (LIQUID_ID + 26)
#define SULPHURIC_ACID (LIQUID_ID + 27)
#define MUSTARD_GAS_LIQUID (LIQUID_ID + 28)
#define LIQUID_DARKNESS (LIQUID_ID + 29)
#define LIQUID_FEAR (LIQUID_ID + 30)
#define ASPHALT (LIQUID_ID + 31)
#define VOMIT (LIQUID_ID + 32)
#define DOG_DROOL (LIQUID_ID + 33)
#define SWEAT (LIQUID_ID + 34)
#define BLOOD (LIQUID_ID + 35)
#define GREEN_BLOOD (LIQUID_ID + 36)
#define BLUE_BLOOD (LIQUID_ID + 37)
#define PLANT_SAP (LIQUID_ID + 38)
#define GLOWING_BLOOD (LIQUID_ID + 39)
#define TROLL_BLOOD (LIQUID_ID + 40)
#define DARK_FROG_BLOOD (LIQUID_ID + 41)
#define SPIDER_BLOOD (LIQUID_ID + 42)
#define ACIDOUS_BLOOD (LIQUID_ID + 43)
#define SICK_BLOOD (LIQUID_ID + 44)
#define LIGHT_FROG_BLOOD (LIQUID_ID + 45)
#define OMMEL_BLOOD (LIQUID_ID + 46)
#define OMMEL_URINE (LIQUID_ID + 47)
#define OMMEL_SWEAT (LIQUID_ID + 48)
#define OMMEL_TEARS (LIQUID_ID + 49)
#define OMMEL_SNOT (LIQUID_ID + 50)
#define MERCURY (LIQUID_ID + 51)
#define QUICK_SILVER (LIQUID_ID + 52)
#define MUD (LIQUID_ID + 53)
#define QUICK_SAND (LIQUID_ID + 54)

#define FLESH_ID (5 << 12)

#define PORK (FLESH_ID + 1)
#define BEEF (FLESH_ID + 2)
#define VENISON (FLESH_ID + 3)
#define MYSTERY_MEAT (FLESH_ID + 4)
#define SNAKE_JERKY (FLESH_ID + 5)
#define TUNA (FLESH_ID + 6)
#define SARDINE (FLESH_ID + 7)
#define GOBLINOID_FLESH (FLESH_ID + 8)
#define FROG_FLESH (FLESH_ID + 9)
#define ELPURI_FLESH (FLESH_ID + 10)
#define HUMAN_FLESH (FLESH_ID + 11)
#define DOLPHIN_FLESH (FLESH_ID + 12)
#define BEAR_FLESH (FLESH_ID + 13)
#define WOLF_FLESH (FLESH_ID + 14)
#define DOG_FLESH (FLESH_ID + 15)
#define ENNER_BEAST_FLESH (FLESH_ID + 16)
#define SPIDER_FLESH (FLESH_ID + 17)
#define JACKAL_FLESH (FLESH_ID + 18)
#define MUTANT_ASS_FLESH (FLESH_ID + 19)
#define BAT_FLESH (FLESH_ID + 20)
#define WERE_WOLF_FLESH (FLESH_ID + 21)
#define KOBOLD_FLESH (FLESH_ID + 22)
#define GIBBERLING_FLESH (FLESH_ID + 23)
#define CAT_FLESH (FLESH_ID + 24)
#define RAT_FLESH (FLESH_ID + 25)
#define ANGEL_FLESH (FLESH_ID + 26)
#define DWARF_FLESH (FLESH_ID + 27)
#define DAEMON_FLESH (FLESH_ID + 28)
#define MAMMOTH_FLESH (FLESH_ID + 29)
#define BLACK_UNICORN_FLESH (FLESH_ID + 30)
#define GRAY_UNICORN_FLESH (FLESH_ID + 31)
#define WHITE_UNICORN_FLESH (FLESH_ID + 32)
#define LION_FLESH (FLESH_ID + 33)
#define BUFFALO_FLESH (FLESH_ID + 34)
#define SNAKE_FLESH (FLESH_ID + 35)
#define ORC_FLESH (FLESH_ID + 36)
#define OSTRICH_FLESH (FLESH_ID + 37)
#define CHAMELEON_FLESH (FLESH_ID + 38)
#define FLOATING_EYE_FLESH (FLESH_ID + 39)
#define MUSHROOM_FLESH (FLESH_ID + 40)
#define MOOSE_FLESH (FLESH_ID + 41)
#define MAGPIE_FLESH (FLESH_ID + 42)
#define SKUNK_FLESH (FLESH_ID + 43)
#define HEDGEHOG_FLESH (FLESH_ID + 44)
#define MUTANT_BUNNY_FLESH (FLESH_ID + 45)
#define HATTIFATTENER_FLESH (FLESH_ID + 46)
#define BLINK_DOG_FLESH (FLESH_ID + 47)
#define MAGIC_MUSHROOM_FLESH (FLESH_ID + 48)
#define SICK_SPIDER_FLESH (FLESH_ID + 49)
#define MIND_WORM_FLESH (FLESH_ID + 50)
#define VAMPIRE_FLESH (FLESH_ID + 51)
#define ELF_FLESH (FLESH_ID + 52)

#define POWDER_ID (6 << 12)

#define GUN_POWDER (POWDER_ID + 1)
#define SALT (POWDER_ID + 2)
#define SNOW (POWDER_ID + 3)
#define SAND (POWDER_ID + 4)
#define RED_SAND (POWDER_ID + 5)
#define BLACK_SAND (POWDER_ID + 6)
#define DIRT (POWDER_ID + 7)
#define SOIL (POWDER_ID + 8)
#define ASH (POWDER_ID + 9)
#define SOOT (POWDER_ID + 10)

#define IRON_ALLOY_ID (7 << 12)

#define PIG_IRON (IRON_ALLOY_ID + 1)
#define IRON (IRON_ALLOY_ID + 2)
#define STEEL (IRON_ALLOY_ID + 3)
#define DWARF_STEEL (IRON_ALLOY_ID + 4)
#define METEORIC_STEEL (IRON_ALLOY_ID + 5)
#define UKKU_STEEL (IRON_ALLOY_ID + 6)
#define ADAMANT (IRON_ALLOY_ID + 7)
#define BLACK_IRON (IRON_ALLOY_ID + 8)
#define SOUL_STEEL (IRON_ALLOY_ID + 9)
#define BLOOD_IRON (IRON_ALLOY_ID + 10)
#define BLOOD_STEEL (IRON_ALLOY_ID + 11)

#define LONG_SWORD 1
#define TWO_HANDED_SWORD 2
#define TWO_HANDED_SCIMITAR 3
#define SPEAR 4
#define AXE 5
#define HALBERD 6
#define MACE 7
#define WAR_HAMMER 8
#define SICKLE 9
#define DAGGER 10
#define SHORT_SWORD 11
#define BASTARD_SWORD 12
#define BATTLE_AXE 13
#define SCYTHE 14
#define QUARTER_STAFF 15
#define HAMMER 16
#define GRAND_STOLLEN_KNIFE 17
#define MAGE_STAFF 18
#define ROLLING_PIN 19
#define FRYING_PAN 20
#define CLAW 21
#define MEAT_CLEAVER 22
#define RUNE_SWORD 23

#define PUPPY_SKULL 1

#define GOROVITS_HAMMER 1
#define GOROVITS_SICKLE 2
#define GOROVITS_SCIMITAR 3

#define CHAIN_MAIL 1
#define PLATE_MAIL 2
#define ARMOR_OF_GREAT_HEALTH 3

#define CHEAP 1
#define EXPENSIVE 2

#define WAND_OF_POLYMORPH 1
#define WAND_OF_STRIKING 2
#define WAND_OF_FIRE_BALLS 3
#define WAND_OF_TELEPORTATION 4
#define WAND_OF_HASTE 5
#define WAND_OF_SLOW 6
#define WAND_OF_RESURRECTION 7
#define WAND_OF_DOOR_CREATION 8
#define WAND_OF_INVISIBILITY 9
#define WAND_OF_CLONING 10
#define WAND_OF_LIGHTNING 11
#define WAND_OF_ACID_RAIN 12
#define WAND_OF_MIRRORING 13
#define WAND_OF_NECROMANCY 14
#define WAND_OF_WEBBING 15
#define WAND_OF_ALCHEMY 16

#define RUNED_WHIP 1

#define BIG_MINE 1

#define CLOAK_OF_INVISIBILITY 1
#define CLOAK_OF_FIRE_RESISTANCE 2
#define CLOAK_OF_ELECTRICITY_RESISTANCE 3
#define CLOAK_OF_ACID_RESISTANCE 4
#define CLOAK_OF_SHADOWS 5

#define LOST_RUBY_FLAMING_SWORD 2

#define BOOT_OF_STRENGTH 1
#define BOOT_OF_AGILITY 2
#define BOOT_OF_KICKING 3

#define GAUNTLET_OF_STRENGTH 1
#define GAUNTLET_OF_DEXTERITY 2

#define RING_OF_FIRE_RESISTANCE 1
#define RING_OF_POLYMORPH_CONTROL 2
#define RING_OF_INFRA_VISION 3
#define RING_OF_TELEPORTATION 4
#define RING_OF_TELEPORT_CONTROL 5
#define RING_OF_POLYMORPH 6
#define RING_OF_POISON_RESISTANCE 7
#define RING_OF_INVISIBILITY 8
#define RING_OF_ELECTRICITY_RESISTANCE 9
#define RING_OF_SEARCHING 10
#define RING_OF_ACID_RESISTANCE 11

#define AMULET_OF_LIFE_SAVING 1
#define AMULET_OF_ESP 2

#define FULL_HELMET 1
#define HELM_OF_PERCEPTION 2
#define HELM_OF_UNDERSTANDING 3
#define HELM_OF_BRILLIANCE 4
#define HELM_OF_ATTRACTIVITY 5
#define GOROVITS_FAMILY_GAS_MASK 6

#define BELT_OF_CARRYING 1
#define BELT_OF_LEVITATION 2

#define SMALL_CHEST 1
#define CHEST 2
#define LARGE_CHEST 3
#define STRONG_BOX 4

#define BRAVERY 1
#define FEAR 2
#define CONFUSION 3
#define HEALING 4
#define PLENTY 5

#define POTTED_CACTUS 1
#define POTTED_PLANT 2
#define DEAD_FISH 3
#define BONE_FISH 4
#define SMALL_CLOCK 5
#define LARGE_CLOCK 6

#define IMPRISONED_FARMER 1
#define CULTIST 2

#define ROOKIE 1
#define VETERAN 2
#define EUNUCH 3
#define PATROL 4
#define SHOP 5
#define ELITE 6
#define MASTER 7
#define GRAND_MASTER 8

#define DARK 1
#define GREATER_DARK 2
#define GIANT_DARK 3
#define LIGHT 4
#define GREATER_LIGHT 5
#define GIANT_LIGHT 6

#define WARRIOR 1
#define WAR_LORD 2

#define BERSERKER 1
#define BUTCHER 2
#define PRINCE 3
#define KING 4

#define CONICAL 1
#define FLAT 2

#define SKELETON_DOG 1

#define LARGE 1
#define GIANT 2
#define ARANEA 3

#define IMPRISONED_HUNTER 1

#define BLACK_BEAR 1
#define GRIZZLY_BEAR 2
#define CAVE_BEAR 3
#define POLAR_BEAR 4
#define PANDA_BEAR 6

#define IMPRISONED_FEMALE 1
/* 2 reserved for ATTNAM */
/* 3 reserved for NEW_ATTNAM */
#define JESTER 4

#define ZOMBIE_OF_KHAZ_ZADM 1
#define IMPRISONED_ZOMBIE 2

#define TORTURING_CHIEF 1
#define WHIP_CHAMPION 2
#define WAR_LADY 3
#define QUEEN 4

#define DRUID 1

#define HUNTER 2
#define PATRIARCH 3
#define ASSASSIN 4
#define MASTER_ASSASSIN 5

#define LORD 1

#define GREATER 1
#define GIANT 2

#define SLAUGHTERER 1
#define SQUAD_LEADER 2
#define OFFICER 3
#define GENERAL 4
#define MARSHAL 5
#define REPRESENTATIVE 6

#define APPRENTICE 1
#define BATTLE_MAGE 2
#define ELDER 3
#define ARCH_MAGE 4

/* Least significant bit defines sex */

#define BABY_MALE 2
#define BABY_FEMALE 3
#define ADULT_MALE 4
#define ADULT_FEMALE 5

#define APPRENTICE_NECROMANCER 1
#define MASTER_NECROMANCER 2
#define IMPRISONED_NECROMANCER 9

#define HUSBAND 1
#define WIFE 2
#define CHILD 3

#define BOY 1
#define GIRL 2

#define LIGHT_ASIAN_SIREN 1
#define DARK_ASIAN_SIREN 2
#define CAUCASIAN_SIREN 3
#define DARK_SIREN 4
#define GREEN_SIREN 5
#define BLUE_SIREN 6
#define RED_SIREN 7
#define PINK_SIREN 8
#define HISPANIC_SIREN 9
#define AMBASSADOR_SIREN 10

#define HATCHLING 1
#define BOIL 2

#define PARQUET 1
#define FLOOR 2
#define GROUND 3
#define GRASS_TERRAIN 4
#define LANDING_SITE 5
#define SNOW_TERRAIN 6
#define DARK_GRASS_TERRAIN 7
#define SAND_TERRAIN 8

#define POOL 1
#define UNDERGROUND_LAKE 2

#define BRICK_FINE 1
#define BRICK_PROPAGANDA 2
#define BRICK_OLD 3
#define BRICK_PRIMITIVE 4
#define BRICK_PRIMITIVE_PROPAGANDA 5
#define STONE_WALL 6
#define ICE_WALL 7
#define BROKEN_WALL 8

#define PINE 1
#define FIR 2
#define HOLY_TREE 3
#define CARPET 4
#define COUCH 5
#define CHAIR 6
#define DOUBLE_BED 9
#define POOL_BORDER 7
#define POOL_CORNER 8
#define PALM 9
#define SNOW_PINE 10
#define SNOW_FIR 11
#define ANVIL 12
#define SHARD 13
#define CACTUS 14
#define OAK 15
#define BIRCH 16
#define TEAK 17
#define DWARF_BIRCH 18

#define SNOW_BOULDER 4

#define OREE_LAIR_ENTRY 300
#define OREE_LAIR_EXIT 400
#define SUMO_ARENA_ENTRY 700
#define SUMO_ARENA_EXIT 800
#define XINROCH_TOMB_ENTRANCE 900
#define XINROCH_TOMB_EXIT 1000

#define BOOK_CASE 1
#define CHEST_OF_DRAWERS 2
#define SHELF 3

#define BROKEN_BARWALL 1
#define SECRET_DOOR 2

#define ROOM_NORMAL 1
#define ROOM_SHOP 2
#define ROOM_CATHEDRAL 3
#define ROOM_LIBRARY 4
#define ROOM_BANANA_DROP_AREA 5
#define ROOM_SUMO_ARENA 6

#define ALL_DUNGEONS  32767

#endif
