#!/bin/sh

set -e
export PATH=/usr/bin:/bin
cd -- "$(dirname -- "$0")"

if [ "$(uname -r | cut -d. -f1)" -ge 11 ]; then
  export DYLD_LIBRARY_PATH=. DYLD_FRAMEWORK_PATH=.
else
  export DYLD_FALLBACK_LIBRARY_PATH=. DYLD_FALLBACK_FRAMEWORK_PATH=.
fi

exec ./ivan
