@if exist *.sav del *.sav
@if exist *.0* del *.0*
@if exist *.1* del *.1*
@if exist *.2* del *.2*
@if exist *.3* del *.3*
@if exist *.4* del *.4*
@if exist *.5* del *.5*
@if exist *.6* del *.6*
@if exist *.7* del *.7*
@if exist *.8* del *.8*
@if exist *.9* del *.9*
@if exist *.wm del *.wm