name: osx-wizmode
on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CI-Build
        shell: bash
        working-directory: ${{runner.workspace}}/build
        env:
          CXXFLAGS: -DWIZARD
        run: |
          echo $PWD
          #export SDL2DIR="$HOME/Downloads/SDL2Frameworks"
          export BUILD_MAC_APP=ON
          export IVAN_BUILD_DIR="$PWD/build"
          mkdir build && cd build
          ../ci/osx/requirements.sh
          ../ci/osx/build.sh
          make install
          ../ci/osx/package.sh
          ls ./osx

