name: osx-wizmode
on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: make-build-dir
        run: mkdir build
      - name: Print github workspace
        run: |
          echo "PWD = $PWD"
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "github.workspace = ${{ github.workspace }}"
          echo "${{runner.workspace}}"
          echo "HOME = $HOME"
      - name: CI-Build
        shell: bash
        working-directory: ${{github.workspace}}/build
        env:
          CXXFLAGS: -DWIZARD
        run: |
          export SDL2DIR="$HOME/Thirdparty/Frameworks"
          export BUILD_MAC_APP=ON
          export IVAN_BUILD_DIR="${{github.workspace}}/build"
          cd build
          ../ci/osx/requirements.sh
          ../ci/osx/build.sh
          make install
          ../ci/osx/package.sh
          ls ./osx

