name: osx-wizmode
on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: make-build-dir
        run: mkdir build
      - name: Print github workspace
        run: |
          echo "PWD = $PWD"
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "github.workspace = ${{ github.workspace }}"
          echo "${{runner.workspace}}"
          echo "HOME = $HOME"
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Show git tag
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: CI-Build
        shell: bash
        working-directory: ${{github.workspace}}/build
        env:
          CXXFLAGS: -DWIZARD
        run: |
          export SDL2DIR="$HOME/Thirdparty/Frameworks"
          export BUILD_MAC_APP=ON
          export IVAN_BUILD_DIR="${{github.workspace}}/build"
          export IVAN_FILE_VERSION=${RELEASE_VERSION#v}
          ../ci/osx/requirements.sh
          ../ci/osx/build.sh
          make install
          ../ci/osx/package.sh
          ls ./osx

      # Attention: you perform the release step when you push a tag, neat huh?
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{github.workspace}}/build/osx/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #GITHUB_REPOSITORY: attnam/ivan
